[build]
  command = "npm install"
  publish = "/"

[build.environment]
  GOOGLE_SERVICE_ACCOUNT = "your-JSON-service-account-here" # DON'T paste in code, set in Netlify UI instead
  RSVP_SPREADSHEET_ID = "your_RSVP_sheet_id"
  RATE_SPREADSHEET_ID = "your_rate_sheet_id"
  SUGGEST_SPREADSHEET_ID = "your_suggest_sheet_id"

[functions]
  directory = "netlify/functions"
