[build]
  command = "npm install"
  publish = "/"

[build.environment]
  GOOGLE_SERVICE_ACCOUNT = "" 
  RSVP_SPREADSHEET_ID = "1ojGEBABMUB0-p1vKd0er03PbapHd3ZXWB3KlyrkowmY"
  RATE_SPREADSHEET_ID = "1-86BOIuWOeINJVJkNojHo-c1T3Ygxm1AgLyedEplgvY"
  SUGGEST_SPREADSHEET_ID = "1WFoa1y-byiCyWb09xKifph6Nzs_9iSCx05fgR9edUbE"

[functions]
  directory = "netlify/functions"
